require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "css",
    "graphql",
    "html",
    "javascript",
    "json",
    "lua",
    "python",
    "rust",
    "svelte",
    "tsx",
    "typescript",
    "prisma",
    "markdown",
    "markdown_inline",
    "astro",
    "prisma",
    "cpp",
    "go",
    "dockerfile",
    "glsl",
    "gitignore",
    "toml",
    "yaml",
  },
  highlight = { enable = true },
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  },
})
