-- local status, typescript = pcall(require, "typescript")
-- if not status then
-- 	return
-- end

-- typescript.setup({
-- 	disable_commands = false,
-- 	debug = false,
-- 	server = {
-- 		capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities()),
-- 		on_attach = function(client)
-- 			client.server_capabilities.document_formatting = false
-- 		end,
-- 		filetypes = { "typescript", "typescriptreact", "typescript.tsx", "javascript", "javascriptreact" },
-- 		cmd = { "typescript-language-server", "--stdio" },
-- 	},
-- })
